# lightning.pytorch==2.1.2
seed_everything: 42
data:
  train_chip_dir: data/cvpr/ny/train/chips/
  train_label_dir: data/cvpr/ny/train/labels/
  val_chip_dir: data/cvpr/ny/val/chips/
  val_label_dir: data/cvpr/ny/val/labels/
  metadata_path: configs/metadata.yaml
  batch_size: 2
  num_workers: 2
  persistent_workers: false
  pin_memory: false
  prefetch_factor: 2
  platform: naip
model:
  num_classes: 7
  ckpt_path: checkpoints/clay-v1.5.ckpt
  lr: 1e-5
  wd: 0.05
  b1: 0.9
  b2: 0.95
trainer:
  accelerator: mps
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  log_every_n_steps: 10
  max_epochs: 40
  accumulate_grad_batches: 8
  default_root_dir: checkpoints
  fast_dev_run: False
  num_sanity_val_steps: 0
  logger:
    - class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: logs/
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints
        auto_insert_metric_name: False
        filename: chesapeake-7class-segment_epoch-{epoch:02d}_val-iou-{val/iou:.4f}
        monitor: val/iou
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
